### ISSUE TITLE
Link | CheeseburgerIM

### ISSUE THREAD

**Issue by CheeseburgerIM** [CheeseburgerIM/repoForGitalk#6]
https://cheeseburgerim.space/link/ 

 如果大佬想加友链，直接在下面评论即可  这是我的友链信息 1234- name: CheeseburgerIM  link: https://CheeseburgerIM.github.io/  avatar: https://img.imgdb.cn/item/5fd07a0e3ffa7d37b3e705e5.jpg  descr: IMF,I’ve got a lot to learn.

**Comment by kohaiy** [comment]
- name: 柯灰小栈
  link: https://www.kohai.top/
  avatar: https://s0.kohai.top/logo_.png
  descr: 业精于勤荒于嬉 行成于思毁于随

**Comment by CheeseburgerIM** [comment]
> @kohaiy
> - name: 柯灰小栈
>   link: https://www.kohai.top/
>   avatar: https://s0.kohai.top/logo_.png
>   descr: 业精于勤荒于嬉 行成于思毁于随

已加^_^

**Comment by TCP404** [comment]
- name: Boii
  link: https://www.boii.xyz
  avatar: https://cdn.jsdelivr.net/gh/TCP404/HEXO-CDN/images/icon/bolgger.png
  descr: 一切皆零，万物归一

**Comment by CheeseburgerIM** [comment]
> @TCP404
> - name: Boii
>   link: https://www.boii.xyz
>   avatar: https://cdn.jsdelivr.net/gh/TCP404/HEXO-CDN/images/icon/bolgger.png
>   descr: 一切皆零，万物归一

已加😁

**Comment by CheeseburgerIM** [comment]
> @TCP404
> - name: Boii
>   link: https://www.boii.xyz
>   avatar: https://cdn.jsdelivr.net/gh/TCP404/HEXO-CDN/images/icon/bolgger.png
>   descr: 一切皆零，万物归一

域名失效了吗，网站进不去了🤥

**Comment by TCP404** [comment]
> @CheeseburgerIM
> > @TCP404
> > - name: Boii
> >   link: https://www.boii.xyz
> >   avatar: https://cdn.jsdelivr.net/gh/TCP404/HEXO-CDN/images/icon/bolgger.png
> >   descr: 一切皆零，万物归一
> 
> 域名失效了吗，网站进不去了🤥

可以进啊。
是不是开了全局VPN 了？
境内访问会解析到coding上，coding的部署比较那啥，有时候会访问不了
境外访问就解析到github上，相对稳定些

**Comment by milkdue** [comment]
```yml
- name: 可以清心
    link: https://www.keyiqingxin.cn/
    avatar: https://cdn.jsdelivr.net/gh/milkdue/cdn@2.9/img/avatar.jpg
    descr: 日夜颠倒头发少，单纯好骗恋爱脑~
```
已添加贵站

**Comment by CheeseburgerIM** [comment]
> @milkdue
> ```yml
> - name: 可以清心
>     link: https://www.keyiqingxin.cn/
>     avatar: https://cdn.jsdelivr.net/gh/milkdue/cdn@2.9/img/avatar.jpg
>     descr: 日夜颠倒头发少，单纯好骗恋爱脑~
> ```
> 已添加贵站

不好意思哈，这两天有点忙，已经加上大佬的友链了>_<

**Comment by CheeseburgerIM** [comment]
> @zjcscut
> - name: Throwable
>   link: https://www.throwx.cn
>   avatar: https://throwable-blog-1256189093.cos.ap-guangzhou.myqcloud.com/mine/doge_avatar.jpg
>   descr: Java、架构、并发编程、源码
>   siteshot: https://throwable-blog-1256189093.cos.ap-guangzhou.myqcloud.com/static/screenshot/snap-001.png

已添加贵站

**Comment by sun0225SUN** [comment]
已添加大佬。respect😘 
```yaml
- name: 小孙同学
  link: https://sunguoqi.com
  avatar: https://cdn.jsdelivr.net/gh/sun0225SUN/photos/img/20210719203648.jpg
  descr: 一个理性的浪漫主义者。
  siteshot: https://cdn.jsdelivr.net/gh/sun0225SUN/photos/img/20210723133309.jpg
```
